Dia: domingo    #########################################################################
  AutoStart0:
    Hora: ''
  AutoStart1:
    Hora: ''
  AutoStart2:
    Hora: ''
  AutoStart3:
    Hora: ''
  AutoStart4:
    Hora: ''
  AutoStart5:
    Hora: ''
  AutoStart6:
    Hora: ''
  AutoStart7:
    Hora: ''
  AutoStart8:
    Hora: ''
  AutoStart9:
    Hora: ''
  AutoStart10:
    Hora: ''
  AutoStart11:
    Hora: ''
  AutoStart12:
    Hora: ''
  AutoStart13:
    Hora: ''
  AutoStart14:
    Hora: ''
  AutoStart15:
    Hora: ''
  AutoStart16:
    Hora: ''
  AutoStart17:
    Hora: ''
  AutoStart18:
    Hora: ''
  AutoStart19:
    Hora: ''
  AutoStart20:
    Hora: ''
  AutoStart21:
    Hora: ''
  AutoStart22:
    Hora: ''
  AutoStart23:
    Hora: ''
  AutoStart24:
    Hora: ''
Dia: segunda    #########################################################################
  AutoStart0:
    Hora: ''
  AutoStart1:
    Hora: ''
  AutoStart2:
    Hora: ''
  AutoStart3:
    Hora: ''
  AutoStart4:
    Hora: ''
  AutoStart5:
    Hora: ''
  AutoStart6:
    Hora: ''
  AutoStart7:
    Hora: ''
  AutoStart8:
    Hora: ''
  AutoStart9:
    Hora: ''
  AutoStart10:
    Hora: ''
  AutoStart11:
    Hora: ''
  AutoStart12:
    Hora: ''
  AutoStart13:
    Hora: ''
  AutoStart14:
    Hora: ''
  AutoStart15:
    Hora: ''
  AutoStart16:
    Hora: ''
  AutoStart17:
    Hora: ''
  AutoStart18:
    Hora: ''
  AutoStart19:
    Hora: ''
  AutoStart20:
    Hora: ''
  AutoStart21:
    Hora: ''
  AutoStart22:
    Hora: ''
  AutoStart23:
    Hora: ''
  AutoStart24:
    Hora: ''
Dia: terca    #########################################################################
  AutoStart0:
    Hora: ''
  AutoStart1:
    Hora: ''
  AutoStart2:
    Hora: ''
  AutoStart3:
    Hora: ''
  AutoStart4:
    Hora: ''
  AutoStart5:
    Hora: ''
  AutoStart6:
    Hora: ''
  AutoStart7:
    Hora: ''
  AutoStart8:
    Hora: ''
  AutoStart9:
    Hora: ''
  AutoStart10:
    Hora: ''
  AutoStart11:
    Hora: ''
  AutoStart12:
    Hora: ''
  AutoStart13:
    Hora: ''
  AutoStart14:
    Hora: ''
  AutoStart15:
    Hora: ''
  AutoStart16:
    Hora: ''
  AutoStart17:
    Hora: ''
  AutoStart18:
    Hora: ''
  AutoStart19:
    Hora: ''
  AutoStart20:
    Hora: ''
  AutoStart21:
    Hora: ''
  AutoStart22:
    Hora: ''
  AutoStart23:
    Hora: ''
  AutoStart24:
    Hora: ''
Dia: quarta    #########################################################################
  AutoStart0:
    Hora: ''
  AutoStart1:
    Hora: ''
  AutoStart2:
    Hora: ''
  AutoStart3:
    Hora: ''
  AutoStart4:
    Hora: ''
  AutoStart5:
    Hora: ''
  AutoStart6:
    Hora: ''
  AutoStart7:
    Hora: ''
  AutoStart8:
    Hora: ''
  AutoStart9:
    Hora: ''
  AutoStart10:
    Hora: ''
  AutoStart11:
    Hora: ''
  AutoStart12:
    Hora: ''
  AutoStart13:
    Hora: ''
  AutoStart14:
    Hora: ''
  AutoStart15:
    Hora: ''
  AutoStart16:
    Hora: ''
  AutoStart17:
    Hora: ''
  AutoStart18:
    Hora: ''
  AutoStart19:
    Hora: ''
  AutoStart20:
    Hora: ''
  AutoStart21:
    Hora: ''
  AutoStart22:
    Hora: ''
  AutoStart23:
    Hora: ''
  AutoStart24:
    Hora: ''
Dia: quinta    #########################################################################
  AutoStart0:
    Hora: ''
  AutoStart1:
    Hora: ''
  AutoStart2:
    Hora: ''
  AutoStart3:
    Hora: ''
  AutoStart4:
    Hora: ''
  AutoStart5:
    Hora: ''
  AutoStart6:
    Hora: ''
  AutoStart7:
    Hora: ''
  AutoStart8:
    Hora: ''
  AutoStart9:
    Hora: ''
  AutoStart10:
    Hora: ''
  AutoStart11:
    Hora: ''
  AutoStart12:
    Hora: ''
  AutoStart13:
    Hora: ''
  AutoStart14:
    Hora: ''
  AutoStart15:
    Hora: ''
  AutoStart16:
    Hora: ''
  AutoStart17:
    Hora: ''
  AutoStart18:
    Hora: ''
  AutoStart19:
    Hora: ''
  AutoStart20:
    Hora: ''
  AutoStart21:
    Hora: ''
  AutoStart22:
    Hora: ''
  AutoStart23:
    Hora: ''
  AutoStart24:
    Hora: ''
Dia: sexta    #########################################################################
  AutoStart0:
    Hora: ''
  AutoStart1:
    Hora: ''
  AutoStart2:
    Hora: ''
  AutoStart3:
    Hora: ''
  AutoStart4:
    Hora: ''
  AutoStart5:
    Hora: ''
  AutoStart6:
    Hora: ''
  AutoStart7:
    Hora: ''
  AutoStart8:
    Hora: ''
  AutoStart9:
    Hora: ''
  AutoStart10:
    Hora: ''
  AutoStart11:
    Hora: ''
  AutoStart12:
    Hora: ''
  AutoStart13:
    Hora: ''
  AutoStart14:
    Hora: ''
  AutoStart15:
    Hora: ''
  AutoStart16:
    Hora: ''
  AutoStart17:
    Hora: ''
  AutoStart18:
    Hora: ''
  AutoStart19:
    Hora: ''
  AutoStart20:
    Hora: ''
  AutoStart21:
    Hora: ''
  AutoStart22:
    Hora: ''
  AutoStart23:
    Hora: ''
  AutoStart24:
    Hora: ''
Dia: sabado    #########################################################################
  AutoStart0:
    Hora: ''
  AutoStart1:
    Hora: ''
  AutoStart2:
    Hora: ''
  AutoStart3:
    Hora: ''
  AutoStart4:
    Hora: ''
  AutoStart5:
    Hora: ''
  AutoStart6:
    Hora: ''
  AutoStart7:
    Hora: ''
  AutoStart8:
    Hora: ''
  AutoStart9:
    Hora: ''
  AutoStart10:
    Hora: ''
  AutoStart11:
    Hora: ''
  AutoStart12:
    Hora: ''
  AutoStart13:
    Hora: ''
  AutoStart14:
    Hora: ''
  AutoStart15:
    Hora: ''
  AutoStart16:
    Hora: ''
  AutoStart17:
    Hora: ''
  AutoStart18:
    Hora: ''
  AutoStart19:
    Hora: ''
  AutoStart20:
    Hora: ''
  AutoStart21:
    Hora: ''
  AutoStart22:
    Hora: ''
  AutoStart23:
    Hora: ''
  AutoStart24:
    Hora: ''